#!/usr/bin/env tsx
/**
 * Unified Design Token Generator
 *
 * Generates CSS Variables for all design tokens from TypeScript constants.
 * This is the Single Source of Truth for design tokens.
 *
 * Generated tokens:
 * - Spacing (from spacing.ts)
 * - Radius (from radius.ts)
 * - Typography (from typography.ts)
 * - Widths & Breakpoints (from widths.ts)
 * - Colors (from color.ts)
 *
 * Usage:
 *   npm run generate:tokens
 *   tsx scripts/generate-design-tokens.ts
 *
 * @version 2.0.0
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  console.log('🚀 Generating design tokens...\n');

  // Import all token modules
  const colorModule = await import('../src/commons/constants/color.js');
  const spacingModule = await import('../src/commons/constants/spacing.js');
  const radiusModule = await import('../src/commons/constants/radius.js');
  const typographyModule = await import('../src/commons/constants/typography.js');
  const widthsModule = await import('../src/commons/constants/widths.js');

  // Generate CSS for each token type
  console.log('📦 Generating Spacing tokens...');
  const spacingCSS = spacingModule.generateSpacingCSSString();

  console.log('📦 Generating Radius tokens...');
  const radiusCSS = radiusModule.generateRadiusCSSString();

  console.log('📦 Generating Typography tokens...');
  const typographyCSS = typographyModule.generateTypographyCSSString();

  console.log('📦 Generating Widths & Breakpoints...');
  const widthsCSS = widthsModule.generateWidthsCSSString();

  console.log('📦 Generating Color tokens...');
  const colorCSS = colorModule.generateCSSString();
  const semanticLightVars = colorModule.generateSemanticCSSVariables('light');
  const semanticLightCSS = Object.entries(semanticLightVars)
    .map(([key, value]) => `  ${key}: ${value};`)
    .join('\n');

  // Read existing theme.css
  const themeCssPath = path.join(__dirname, '../src/styles/theme.css');
  let existingCSS = '';

  try {
    existingCSS = fs.readFileSync(themeCssPath, 'utf-8');
  } catch (error) {
    console.warn('⚠️  theme.css not found, creating new file');
  }

  // Build new auto-generated section
  const autoGenStart = '/* AUTO-GENERATED DESIGN TOKENS - START */';
  const autoGenEnd = '/* AUTO-GENERATED DESIGN TOKENS - END */';

  const newTokenSection = `${autoGenStart}
  /* ============================================================================
     DO NOT EDIT THIS SECTION MANUALLY
     This section is auto-generated by: npm run generate:tokens
     Source: TypeScript design token files in src/commons/constants/
     ============================================================================ */

  /* ----------------------------------------------------------------------------
     SPACING TOKENS
     Source: spacing.ts
     Generated: ${new Date().toISOString()}
     ---------------------------------------------------------------------------- */

${spacingCSS}

  /* ----------------------------------------------------------------------------
     RADIUS TOKENS
     Source: radius.ts
     ---------------------------------------------------------------------------- */

${radiusCSS}

  /* ----------------------------------------------------------------------------
     TYPOGRAPHY TOKENS
     Source: typography.ts
     ---------------------------------------------------------------------------- */

${typographyCSS}

  /* ----------------------------------------------------------------------------
     WIDTHS & BREAKPOINTS
     Source: widths.ts
     ---------------------------------------------------------------------------- */

${widthsCSS}

  /* ----------------------------------------------------------------------------
     COLOR TOKENS (Primitive)
     Source: color.ts
     ---------------------------------------------------------------------------- */

${colorCSS}

  /* ----------------------------------------------------------------------------
     COLOR TOKENS (Semantic - Light Mode)
     Source: color.ts
     ---------------------------------------------------------------------------- */

${semanticLightCSS}

  /* ============================================================================
     END OF AUTO-GENERATED SECTION
     ============================================================================ */
${autoGenEnd}`;

  // Replace auto-generated section or create new file
  let newCSS: string;

  if (existingCSS.includes(autoGenStart)) {
    // Replace existing auto-generated section
    const regex = new RegExp(
      `${autoGenStart.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${autoGenEnd.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`,
      'g'
    );
    newCSS = existingCSS.replace(regex, newTokenSection);
    console.log('\n✅ Updated existing auto-generated section');
  } else {
    // Create new file with @theme wrapper
    newCSS = `@theme {
${newTokenSection}

  /* ============================================================================
     MANUAL OVERRIDES
     ============================================================================
     Add custom CSS variables below this section.
     These will NOT be overwritten by auto-generation.
     ============================================================================ */

  /* Shadows (not auto-generated) */
  --shadow-xs: 0px 1px 2px rgba(10, 13, 18, 0.05);
  --shadow-sm: 0px 1px 3px rgba(10, 13, 18, 0.1), 0px 1px 2px -1px rgba(10, 13, 18, 0.1);
  --shadow-md: 0px 4px 6px -1px rgba(10, 13, 18, 0.1), 0px 2px 4px -2px rgba(10, 13, 18, 0.06);
  --shadow-lg: 0px 12px 16px -4px rgba(10, 13, 18, 0.08), 0px 4px 6px -2px rgba(10, 13, 18, 0.03), 0px 2px 2px -1px rgba(10, 13, 18, 0.04);
  --shadow-xl: 0px 20px 24px -4px rgba(10, 13, 18, 0.08), 0px 8px 8px -4px rgba(10, 13, 18, 0.03), 0px 3px 3px -1.5px rgba(10, 13, 18, 0.04);
  --shadow-2xl: 0px 24px 48px -12px rgba(10, 13, 18, 0.18), 0px 4px 4px -2px rgba(10, 13, 18, 0.04);
  --shadow-3xl: 0px 32px 64px -12px rgba(10, 13, 18, 0.14), 0px 5px 5px -2.5px rgba(10, 13, 18, 0.04);

  /* Animations (not auto-generated) */
  --animate-marquee: marquee 60s linear infinite;
  --animate-caret-blink: caret-blink 1s infinite;

  @keyframes marquee {
    0% {
      transform: translateX(0);
    }
    100% {
      transform: translateX(-100%);
    }
  }

  @keyframes caret-blink {
    0%, 50% {
      opacity: 1;
    }
    51%, 100% {
      opacity: 0;
    }
  }
}

@layer base {
  /* Dark mode variables */
  .dark-mode {
    /* Dark mode overrides will be added here */
  }
}

/* ============================================================================
   OSM BRAND OVERRIDES
   ============================================================================
   These overrides ensure OSM's brand identity is preserved.
   DO NOT DELETE THIS SECTION.
   ============================================================================ */

@theme {
  /* OSM Primary Brand Colors */
  --color-brand-600: rgb(105 65 198);  /* OSM brand.600 = #6941c6 */
  --color-brand-700: rgb(83 56 158);   /* OSM brand.700 = #53389e */

  /* OSM Typography - Font Families */
  --font-display: 'DM Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  --font-body: 'Poppins', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}
`;
    console.log('\n✅ Created new theme.css with auto-generated section');
  }

  // Write theme.css
  fs.writeFileSync(themeCssPath, newCSS, 'utf-8');

  // Print summary
  console.log('\n📊 Generation Summary:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`📁 Output: ${themeCssPath}`);
  console.log('📦 Generated tokens:');
  console.log('   ✓ Spacing (17 variables)');
  console.log('   ✓ Radius (11 variables)');
  console.log('   ✓ Typography (26+ variables)');
  console.log('   ✓ Widths & Breakpoints (3 variables)');
  console.log('   ✓ Colors (Primitive + Semantic)');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('✅ Design tokens generated successfully!\n');
}

main().catch(error => {
  console.error('❌ Error generating design tokens:', error);
  process.exit(1);
});
